package phases

import (
	"context"
	"fmt"
	"os/exec"
	"strings"

	"github.com/jdfalk/migrate-loop/internal/state"
)

// PR pushes the worktree branch and, if `gh` is available on PATH, opens a
// pull request with a summary body describing the migrate-loop run.
func PR(ctx context.Context, st *state.State, d Deps) error {
	if err := d.Worktree.Push(ctx); err != nil {
		return fmt.Errorf("pr: push: %w", err)
	}
	body := buildPRBody(st)
	if _, err := exec.LookPath("gh"); err != nil {
		// gh not installed; leave the push and let the human open PR manually
		return nil
	}
	cmd := exec.CommandContext(ctx, "gh", "pr", "create",
		"--title", fmt.Sprintf("migrate: %s (test-first via migrate-loop)", st.Slug),
		"--body", body)
	cmd.Dir = d.Worktree.Path
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("gh pr create: %w\n%s", err, out)
	}
	return nil
}

func buildPRBody(st *state.State) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## migrate-loop run summary\n\n")
	fmt.Fprintf(&b, "- Slug: `%s`\n", st.Slug)
	fmt.Fprintf(&b, "- Iterations: %d/%d main, %d/%d coverage\n", st.BudgetUsed, st.Budget, st.CoverageBudgetUsed, st.CoverageBudget)
	fmt.Fprintf(&b, "- Total cost: $%.2f\n", st.TotalCostUSD)
	fmt.Fprintf(&b, "- Redirect used: %v\n", st.RedirectUsed)
	if len(st.OscillationLog) > 0 {
		fmt.Fprintf(&b, "- Oscillations: %s\n", summarizeOscillation(st.OscillationLog))
	}
	fmt.Fprintf(&b, "\nGenerated by migrate-loop. See commit graph for the test-first history.\n")
	return b.String()
}
