package phases

import (
	"strings"
	"testing"

	"github.com/jdfalk/migrate-loop/internal/state"
)

func TestPR_BuildsBody(t *testing.T) {
	st := &state.State{
		Slug:               "demo",
		Phase:              state.PhasePR,
		Budget:             50,
		BudgetUsed:         7,
		CoverageBudget:     15,
		CoverageBudgetUsed: 1,
		TotalCostUSD:       0.42,
		OscillationLog:     []state.OscillationEvent{{Iteration: 4, Note: "x"}},
	}
	body := buildPRBody(st)
	for _, want := range []string{"7/50", "0.42", "iter4:x", "Generated by migrate-loop"} {
		if !strings.Contains(body, want) {
			t.Errorf("PR body missing %q\nbody:\n%s", want, body)
		}
	}
}
