# file: .github/workflows/ci.yml
# version: 3.0.0

name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: falkcorp/github-common/.github/workflows/reusable-ci.yml@6694e50b2f6564b24cda9b1b78278e9af714c9d9 # latest
    with:
      go-version: '1.25'
    secrets: inherit
