# file: .github/workflows/ci.yml
# version: 3.0.0

name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: falkcorp/github-common/.github/workflows/reusable-ci.yml@9796749d08eccc90b20b23ab3a97af28a73a14a0 # latest
    with:
      go-version: '1.25'
    secrets: inherit
